version: 2
updates:
  # Elixir / Hex
  - package-ecosystem: "mix"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(hex)"

  # Dockerfile
  - package-ecosystem: "docker"
    directories: ["/", ".devcontainer/"]
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(docker)"

  # docker-compose.yaml
  - package-ecosystem: "docker-compose"
    directories: ["/", ".devcontainer/"]
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(compose)"

  # Dev Containers (.devcontainer/**)
  - package-ecosystem: "devcontainers"
    directory: ".devcontainer/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(devcont)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(ci)"

  # Bun (package.json + bun.lock)
  - package-ecosystem: "bun"
    directory: "/assets"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "chore(bun)"
